[2025-03-16T04:39:12.001+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-16T04:39:12.013+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.gold_layer_group.load_dimensions_and_facts manual__2025-03-16T04:38:54.397745+00:00 [queued]>
[2025-03-16T04:39:12.019+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.gold_layer_group.load_dimensions_and_facts manual__2025-03-16T04:38:54.397745+00:00 [queued]>
[2025-03-16T04:39:12.019+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2025-03-16T04:39:12.028+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): gold_layer_group.load_dimensions_and_facts> on 2025-03-16 04:38:54.397745+00:00
[2025-03-16T04:39:12.035+0000] {standard_task_runner.py:72} INFO - Started process 1955 to run task
[2025-03-16T04:39:12.038+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'gold_layer_group.load_dimensions_and_facts', 'manual__2025-03-16T04:38:54.397745+00:00', '--job-id', '173', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmpjbe7p637']
[2025-03-16T04:39:12.039+0000] {standard_task_runner.py:105} INFO - Job 173: Subtask gold_layer_group.load_dimensions_and_facts
[2025-03-16T04:39:12.076+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.gold_layer_group.load_dimensions_and_facts manual__2025-03-16T04:38:54.397745+00:00 [running]> on host c891f3a5df31
[2025-03-16T04:39:12.161+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='gold_layer_group.load_dimensions_and_facts' AIRFLOW_CTX_EXECUTION_DATE='2025-03-16T04:38:54.397745+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-16T04:38:54.397745+00:00'
[2025-03-16T04:39:12.162+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-16T04:39:12.166+0000] {log.py:232} WARNING - 2025-03-16 04:39:12.165 | INFO     | data_pipeline.gold.load_to_dwh:load_dimensions_and_facts:215 - Loading features into Data Warehouse
[2025-03-16T04:39:12.171+0000] {log.py:232} WARNING - 2025-03-16 04:39:12.171 | INFO     | data_pipeline.gold.load_to_dwh:load_dimensions_and_facts:221 - Available columns: ['VendorID', 'lpep_pickup_datetime', 'lpep_dropoff_datetime', 'store_and_fwd_flag', 'RatecodeID', 'PULocationID', 'DOLocationID', 'passenger_count', 'trip_distance', 'fare_amount', 'extra', 'mta_tax', 'tip_amount', 'tolls_amount', 'ehail_fee', 'improvement_surcharge', 'total_amount', 'payment_type', 'trip_type', 'congestion_surcharge', 'record_hash', 'processed_date', 'processing_pipeline', 'valid']
[2025-03-16T04:39:12.172+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-03-16T04:39:12.173+0000] {base.py:84} INFO - Retrieving connection 'postgres_***'
[2025-03-16T04:39:12.176+0000] {sql.py:624} INFO - Running statement: CREATE SCHEMA IF NOT EXISTS feature_store;, parameters: None
[2025-03-16T04:39:12.178+0000] {log.py:232} WARNING - 2025-03-16 04:39:12.178 | INFO     | data_pipeline.gold.load_to_***:create_trip_features:171 - Creating trip features table
[2025-03-16T04:39:12.180+0000] {log.py:232} WARNING - 2025-03-16 04:39:12.180 | ERROR    | data_pipeline.gold.load_to_***:load_dimensions_and_facts:232 - Failed to load trip features: "['trip_id', 'vendor_id', 'pickup_location_id', 'dropoff_location_id', 'rate_code_id', 'event_timestamp', 'trip_duration_minutes', 'avg_speed_mph', 'is_shared_ride', 'is_suspicious', 'created_timestamp'] not in index"
[2025-03-16T04:39:12.180+0000] {log.py:232} WARNING - 2025-03-16 04:39:12.180 | INFO     | data_pipeline.gold.load_to_***:create_location_features:196 - Creating location features table
[2025-03-16T04:39:12.181+0000] {log.py:232} WARNING - 2025-03-16 04:39:12.181 | ERROR    | data_pipeline.gold.load_to_***:load_dimensions_and_facts:240 - Failed to load location features: "None of [Index(['location_id', 'latitude', 'longitude', 'event_timestamp',\n       'current_demand', 'available_taxis', 'surge_multiplier',\n       'weather_condition', 'traffic_level', 'created_timestamp'],\n      dtype='object')] are in the [columns]"
[2025-03-16T04:39:12.182+0000] {python.py:240} INFO - Done. Returned value was: {'success': True, 'trip_features_loaded': 0, 'location_features_loaded': 0}
[2025-03-16T04:39:12.213+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-16T04:39:12.214+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=gold_layer_group.load_dimensions_and_facts, run_id=manual__2025-03-16T04:38:54.397745+00:00, execution_date=20250316T043854, start_date=20250316T043912, end_date=20250316T043912
[2025-03-16T04:39:12.252+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-16T04:39:12.271+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-16T04:39:12.273+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
